on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: IRNYH8W4RQ3UEH91RF4I
          secret_access_key: tfbgYv43z6D5mBaQfjm2XfePdFEo1zU4mYXY8RDX
          region: 'cn-north-4'

      # ${{ github.workspace }}为action运行时的工作目录
      - name: Echo Workspace of Action
        run: echo ${{ github.workspace }}

      # ${{ runner.temp }}为运行器临时目录的路径
      - name: Echo Temporary Directory on the Runner
        run: echo ${{ runner.temp }}
      
      # 上传文件到华为云OBS
      - name: Upload To HuaweiCloud OBS
        uses: huaweicloud/obs-helper@v1.3.0
        with:
          bucket_name: 'dxh'
          local_file_path: |
            ./data
            ./image
            ./util
            ./training.py
            ./workflow.py
          obs_file_path: github-actions-demo
          operation_type: 'upload'
          include_self_folder: true

      - name: Build and deploy model
        run: |
          cd requirements
          pip3 install -r requirements.txt
          python3 workflow.py
