name: github actions with modelarts demo
on: [push]

env:
  REGION_ID: 'cn-north-4'
  SWR_ORGANIZATION: 'default'
  IMAGE_NAME: 'modelarts-pytorch'

jobs:
  connect_to_hwcloud:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # ${{ github.workspace }}为action运行时的工作目录
      - name: Echo Workspace of Action
        run: echo ${{ github.workspace }}

      # ${{ runner.temp }}为运行器临时目录的路径
      - name: Echo Temporary Directory on the Runner
        run: echo ${{ runner.temp }}

      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }}
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: ${{ env.REGION_ID}}
 
      # 上传文件到华为云OBS
      - name: Upload To HuaweiCloud OBS
        uses: huaweicloud/obs-helper@v1.3.0
        with:
          bucket_name: 'dxh'
          local_file_path: |
            ./data
            ./util
            ./training.py
            ./workflow.py
          obs_file_path: github-actions-demo
          operation_type: 'upload'
          include_self_folder: true

      #构建ModelArts自定义镜像
      - name: Login to SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: ${{ env.REGION_ID }}

      - name: Build Image
        run: |
          curl -fsSL get.docker.com -o get-docker.sh
          sh get-docker.sh
          cd docker-image
          wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh
          wget https://download.pytorch.org/whl/cu102/torch-1.9.1%2Bcu102-cp37-cp37m-linux_x86_64.whl
          wget https://download.pytorch.org/whl/cu102/torchaudio-0.10.2%2Bcu102-cp37-cp37m-linux_x86_64.whl
          wget https://download.pytorch.org/whl/cu102/torchvision-0.11.0%2Bcu102-cp37-cp37m-linux_x86_64.whl
          ducker build . -t pytorch:1.8.1-cuda10.2
          cd ..
      
      - name: Tag and Push Image to Huawei Cloud SWR
        id: push-image
        env:
          SWR_REGISTRY: swr.${{ env.REGION_ID }}.myhuaweicloud.com
          SWR_ORGANIZATION: ${{ env.SWR_ORGANIZATION }}
          IMAGE_TAG: ${{ github.sha }} # 镜像版本,这里是使用代码commitid sha值， 用户可以修改成自己需要的。
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          docker build -t $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG .
          docker push $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG
          echo "::set-output name=image::$SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG"

      #安装ModelArts相关sdk依赖，通过sdk执行ModelArts的workflow
      - name: Build and deploy model
        run: |
          cd requirements
          pip3 install -r requirements.txt
          cd ..
          python3 ./workflow.py --access_key=${{secrets.ACCESSKEY}} --secret_key=${{secrets.SECRETACCESSKEY}} --project_id=07ccb07b350010232fb6c00b03d8c78e --obs_bucket_name=dxh --project_name=github-actions-demo
