name: Deploy Workflow to ModelArts

on: [push]
jobs:
  workflow_demo:
    runs-on: ubuntu-latest

    steps:
      # - name: Authenticate to Huawei Cloud
      #   uses: huaweicloud/auth-action@v1.1.0
      #   with: 
      #     access_key_id: ${{ secrets.ACCESSKEY }} 
      #     secret_access_key: ${{ secrets.SECRETACCESSKEY }}
      #     region: 'cn-north-4'

      - name: Echo Workspace of Action
        run: echo ${{ github.workspace }}
      
      # 上传文件到华为云OBS
      - name: Upload To HuaweiCloud OBS
        uses: huaweicloud/obs-helper@v1.2.0
        id: upload_file_to_obs
        with:
          access_key: 'IRNYH8W4RQ3UEH91RF4I'
          secret_key: 'tfbgYv43z6D5mBaQfjm2XfePdFEo1zU4mYXY8RDX'
          region: 'cn-north-4'
          bucket_name: 'dxh'
          local_file_path: 'pipeline_coll/data'
          obs_file_path: 'github-actions-demo'
          operation_type: 'upload'
          include_self_folder: true
